name: CI - Run Backend Tests Only

on:
  push:
    branches: ['*']
  pull_request:
  workflow_dispatch:

jobs:
  run-backend-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install backend dependencies
        run: npm install
        working-directory: Backend

      - name: Run ESLint (lint check)
        run: npm run lint
        working-directory: Backend

      - name: Run backend tests
        run: npm test
        working-directory: Backend
