name: CI - Run Backend & Frontend Tests Only

on:
  push:
    branches: ['*']
  pull_request:
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      # Backend Lint & Test
      - name: Install backend dependencies
        run: npm install
        working-directory: Backend

      - name: Fix backend ESLint permissions
        run: chmod +x node_modules/.bin/eslint
        working-directory: Backend

      - name: Run backend ESLint
        run: npx eslint .
        working-directory: Backend

      - name: Run backend tests
        run: npm test
        working-directory: Backend

      # Frontend Lint
      - name: Install frontend dependencies
        run: npm install
        working-directory: Frontend

      - name: Run frontend ESLint
        run: npx eslint . --ext .js,.vue
        working-directory: Frontend
