name: Deploy to Droplet

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install frontend dependencies and build
        working-directory: ./Frontend
        run: |
          npm install
          npm run build
          npm run build:web

      - name: Deploy backend and frontend
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: |
            Backend/**
            Frontend/dist-web/**
          target: '~/FinalYearProject'

      - name: Restart PM2 on server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/FinalYearProject/Backend
            pm2 restart all
