name: Deploy to Droplet

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code (for workflow context only)
        uses: actions/checkout@v3

      - name: Deploy and build on Droplet
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |

            cd ~/FinalYearProject
            git reset --hard
            git pull origin main


            cd Frontend
            npm install
            npm run build
            npm run build:web


            cd ../Backend
            pm2 restart notemax
